# Node Labels
PERSON_LABEL = "Person"
ASTROFEATURE_LABEL = "AstroFeature"
HDFEATURE_LABEL = "HDFeature"
TYPOLOGYRESULT_LABEL = "TypologyResult"

# Relationship Types
HAS_FEATURE_REL = "HAS_FEATURE"
INFLUENCES_REL = "INFLUENCES"
CONFLICTS_WITH_REL = "CONFLICTS_WITH"
HAS_TYPOLOGY_RESULT_REL = "HAS_TYPOLOGY_RESULT"